<?php
/**
 * @var Magenest\Movie\Block\TestPage $block
 */


?>
<button id="open_modal" type="button">Open Modal</button>
<button id="login" type="button">Open Magento Login Modal</button>
<button id="custom_login" type="button" onclick="alert('hello')">Open Custom Login Modal</button>
<div id="popup-modal" style="display:none;">
    <h1> Hello World! </h1>
    <?php echo $block->getImage().'/icons/favicon.ico'?><br>
    <?php echo $block->getImage().'/bg-01.jpg'?><br>
    <?php echo $block->getImage().'/icons/icon-google.png'?><br>
    <?php echo $block->getAssetUrl('Magenest_Movie::vendor/daterangepicker/moment.min.js')?><br>
    <?php echo $block->getAssetUrl('Magenest_Movie::vendor/bootstrap/css/bootstrap.min.css')?>
</div>
<div id="login-popup-modal" style="display:none;">
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>Login V5</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="<?php echo $block->getImage().'/icons/favicon.ico'?>"/>
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/bootstrap/css/bootstrap.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::fonts/font-awesome-4.7.0/css/font-awesome.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::fonts/Linearicons-Free-v1.0.0/icon-font.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/animate/animate.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/css-hamburgers/hamburgers.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/animsition/css/animsition.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/select2/select2.min.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::vendor/daterangepicker/daterangepicker.css')?>">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::css/util.css')?>">
        <link rel="stylesheet" type="text/css" href="<?php echo $block->getAssetUrl('Magenest_Movie::css/main.css')?>"">
        <!--===============================================================================================-->
    </head>
    <body>

    <div class="limiter">
        <div class="container-login100" style="background-image: url('<?php echo $block->getImage().'/bg-01.jpg'?>');">
            <div class="wrap-login100 p-l-110 p-r-110 p-t-62 p-b-33">
                <form class="login100-form validate-form flex-sb flex-w">
					<span class="login100-form-title p-b-53">
						Sign In With
					</span>

                    <a href="#" class="btn-face m-b-20" >
                        <i class="fa fa-facebook-official" ></i>
                        Facebook
                    </a>

                    <a href="#" class="btn-google m-b-20">
                        <img src="<?php echo $block->getImage().'/icons/icon-google.png'?>" alt="GOOGLE">
                        Google
                    </a>

                    <div class="p-t-31 p-b-9">
						<span class="txt1">
							Username
						</span>
                    </div>
                    <div class="wrap-input100 validate-input" data-validate = "Username is required">
                        <input class="input100" type="text" name="username" >
                        <span class="focus-input100"></span>
                    </div>

                    <div class="p-t-13 p-b-9">
						<span class="txt1">
							Password
						</span>

                        <a href="#" class="txt2 bo1 m-l-5">
                            Forgot?
                        </a>
                    </div>
                    <div class="wrap-input100 validate-input" data-validate = "Password is required">
                        <input class="input100" type="password" name="pass" >
                        <span class="focus-input100"></span>
                    </div>

                    <div class="container-login100-form-btn m-t-17">
                        <button class="login100-form-btn">
                            Sign In
                        </button>
                    </div>

                    <div class="w-full text-center p-t-55">
						<span class="txt2">
							Not a member?
						</span>

                        <a href="#" class="txt2 bo1">
                            Sign up now
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>


<!--    <div id="dropDownSelect1"></div>-->
<!---->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/jquery/jquery-3.2.1.min.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/animsition/js/animsition.min.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/bootstrap/js/popper.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/bootstrap/js/bootstrap.min.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/select2/select2.min.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/daterangepicker/moment.min.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/daterangepicker/daterangepicker.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::vendor/countdowntime/countdowntime.js')?><!--"></script>-->
<!--    <script src="--><?php //echo $block->getAssetUrl('Magenest_Movie::js/main.js')?><!--"></script>-->

    </body>
    </html>
</div>

<!--<script type="text/javascript">-->
<!--    require([ 'jquery', 'jquery/ui'], function($){-->
<!--        $(document).on("click","#open_modal", function() {-->
<!--            alert('Hello World!');-->
<!--        });-->
<!--    });-->
<!--</script>-->

<!--------------------magento alert modal------------------->

<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-modal'));
            $("#open_modal").on('click',function(){
                $("#popup-modal").modal("openModal");
            });

        }
    );
</script>

<!--------------------Login magento alert modal------------------->
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function($, modal) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'popup modal title',
                buttons: [{
                    text: $.mage.__('Continue'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#login-popup-modal'));
            $("#login").on('click',function(){
                $("#login-popup-modal").modal("openModal");
            });

        }
    );
</script>