<?php
/**@var Magenest\Movie\Block\Adminhtml\Second\NumberOfEntity $block*/

    $countP = 1;
    foreach ($block->getProductCollection() as $value)
    {
        echo $countP.' | '.$value->getData('name').'<br>';
        $countP++;
    }
    $quantityP = $countP - 1;
    echo '<strong>Numbers of product: </strong>' .$quantityP . '<br>';

    $countC = 1;
    foreach ($block->getCustomerCollection() as $value)
    {
        echo $countC.' | '.$value->getData('email').'<br>';
        $countC++;
    }
    $quantityC = $countC - 1;
    echo "<strong>Numbers of customer: </strong>" . $quantityC .'<br>';
    echo "<strong>Numbers of order: </strong>". $block->getNumbersOfOrder() . '<br>';
    echo "<strong>Numbers of invoice: </strong>". $block->getNumbersOfInvoice() . '<br>';
    echo "<strong>Numbers of credit memo: </strong>". $block->getNumbersOfCreditMemo() . '<br>';
?>