<?php
/** @var \Magenest\Movie\Block\CustomerInfo $block*/
?>

<strong class="box-title">
    <span><?= $block->escapeHtml(__('Customer Information')) ?></span>
</strong>
<div class="box-content">
    <img src="<?php echo $block->getImage()?>" alt="" width="100" height="100">

    <p>
        <?= $block->escapeHtml(__('Avartar: %1', $block->getImage())) ?><br>
        <?= $block->escapeHtml(__('Username: %1', $block->getName())) ?><br>
        <?= $block->escapeHtml(__('Email: %1', $block->getEmail())) ?><br>
        <?= $block->escapeHtml(__('Email: %1', $block->getPhone())) ?><br>
    </p>


</div>
