<?php
/** @var \Magenest\Movie\Block\CustomerInfo $block*/
?>

<strong class="box-title">
    <h2><?= $block->escapeHtml(__('Customer Information')) ?></h2>
</strong>

<table class="data table" id="test-data-table">
    <thead>
    <tr>
        <th scope="col" class="col avatar">Avatar</th>
        <th scope="col" class="col name">Name</th>
        <th scope="col" class="col email">Email</th>
        <th scope="col" class="col phone">Phone Number</th>
    </tr>
    </thead>
    <tbody>
        <tr>
            <td data-th="avatar" class="col avatar"> <img src="<?php echo $block->getImage()?>" alt="" width="100" height="100"><br></td>
            <td data-th="name" class="col name"><?= $block->escapeHtml(__($block->getName())) ?><br></td>
            <td data-th="email" class="col email"><?= $block->escapeHtml(__($block->getEmail())) ?><br></td>
            <td data-th="phone" class="col phone"><?= $block->escapeHtml(__($block->getPhone())) ?><br></td>
        </tr>
    </tbody>
</table>
